name: Build and Release a Package

# Trigger when a release is tagged.
on:
  release:
    types: [created]

# Trigger when a push happens on main - this is the same as "on merge to main"
# on:
#   push:
#     branches:
#       - main

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Node Dependencies
        run: npm install
      - name: NPM Build
        run: npm install